version: '3'

services:
  web:
    working_dir: /project
    #      image: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/dockerNginx
    container_name: lausincere_nginx
    volumes:
    - .:/project
    - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
    #        - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "83:83"
    #        - "443:443"
    restart: always
    depends_on:
    - lausincere_php

  lausincere_php:
    working_dir: /project
    build:
      context: .
      dockerfile: ./docker/php/dockerPhp
    restart: always
    container_name: lausincere_php
    expose:
    - "9000"
    volumes:
    - .:/project
#        - ./docker/conf/php:/usr/local/etc:ro

networks:
  default:
    external:
      name: lat_project

#mysql:
#  image: mysql:5.7
#  container_name: mysql
#  ports:
#  - "3306:3306"
#  volumes:
#  - ./data:/var/lib/mysql
#  environment:
#    MYSQL_ROOT_PASSWORD: 12345
#
#dishrank:
#  image: webdevops/php-apache-dev
#  container_name: random
#  volumes:
#  - ./:/app
#  ports:
#  - "5566:80"
